### ISSUE TITLE
Missing expo-build-properties dependency

### ISSUE THREAD

**Issue by lachenmayer** [expo/config-plugins#157]
### Summary

Hey there, I'm currently trying to install `ffmpeg-kit-react-native` using the config plugin.

It seems there's a small dependency (or documentation?) issue: after installing `ffmpeg-kit-react-native` and `@config-plugins/ffmpeg-kit-react-native`, `eas build` fails with `Error: Cannot find module 'expo-build-properties'`.

From what I can tell, a simple solution would be to add `expo-build-properties` to `@config-plugins/ffmpeg-kit-react-native`'s dependencies, as it is imported here:

https://github.com/expo/config-plugins/blob/a6d6b1dff8a3bffbee6e7cb767e0b71ede0ee02b/packages/ffmpeg-kit-react-native/src/withFFMPEG.ts#L6

This was introduced in #114. In that PR, `expo-build-properties` was added as a dependency to another config plugin (`react-native-webrtc` - [see diff](https://github.com/expo/config-plugins/pull/114/files#diff-7fe03176d3e12d8adf61cda81ecd5cc7bf82fe0a3398e6ed458f342514c23509R41)), so this just seems like a small oversight.

Alternatively, this could be added as a `peerDependency` - in that case, it would be great to update the installation docs to include adding the `expo-build-properties` dependency.

Duplicate bug report (closed, but not fixed): #148 

### Config Plugin

@config-plugins/ffmpeg-kit-react-native

### What platform(s) does this occur on?

Android, iOS

### SDK Version

47

### Reproducible demo

In a fresh Expo project...

1. `yarn add ffmpeg-kit-react-native @config-plugins/ffmpeg-kit-react-native`
2. `yarn eas build --platform all`

This fails with the following error, no build is submitted to EAS:

```
    Error: Cannot find module 'expo-build-properties'
    Require stack:
    - ...redacted.../app/node_modules/@config-plugins/ffmpeg-kit-react-native/build/withFFMPE
    G.js
    - ...redacted.../app/node_modules/@config-plugins/ffmpeg-kit-react-native/app.plugin.js
    - ...redacted.../app/node_modules/eas-cli/node_modules/@expo/config-plugins/build/utils/p
    lugin-resolver.js
    - ...redacted.../app/node_modules/eas-cli/node_modules/@expo/config-plugins/build/plugins
    /withStaticPlugin.js
    - ...redacted.../app/node_modules/eas-cli/node_modules/@expo/config-plugins/build/plugins
    /withPlugins.js
    - 
    ...redacted.../app/node_modules/eas-cli/node_modules/@expo/config-plugins/build/index.js
    - ...redacted.../app/node_modules/eas-cli/build/project/ios/bundleIdentifier.js
    - ...redacted.../app/node_modules/eas-cli/build/credentials/ios/api/GraphqlClient.js
    - ...redacted.../app/node_modules/eas-cli/build/credentials/context.js
    - ...redacted.../app/node_modules/eas-cli/build/submit/context.js
    - ...redacted.../app/node_modules/eas-cli/build/build/runBuildAndSubmit.js
    - ...redacted.../app/node_modules/eas-cli/build/commands/build/index.js
    - ...redacted.../app/node_modules/eas-cli/node_modules/@oclif/core/lib/module-loader.js
    - ...redacted.../app/node_modules/eas-cli/node_modules/@oclif/core/lib/config/plugin.js
    - ...redacted.../app/node_modules/eas-cli/node_modules/@oclif/core/lib/config/config.js
    - ...redacted.../app/node_modules/eas-cli/node_modules/@oclif/core/lib/config/index.js
    - ...redacted.../app/node_modules/eas-cli/node_modules/@oclif/core/lib/command.js
    - ...redacted.../app/node_modules/eas-cli/node_modules/@oclif/core/lib/index.js
    - ...redacted.../app/node_modules/eas-cli/bin/run
    Code: MODULE_NOT_FOUND
```

3. `yarn add expo-build-properties`, and re-run the EAS build command: build is submitted as expected ✅

**Comment by fruitptr** [comment]
I'm experiencing the same issue. Did you find a fix?

**Comment by johnhaup** [comment]
expo-build-properties keeps giving me a warning in VSCode:

`Plugin not found: expo-build-properties`

App builds fine in sim but crashes on device (the classic tale).

**Comment by Trevaughn-TechBridge** [comment]
> In my `app.json`, `expo-build-properties` keeps giving me a warning in VSCode:
> 
> `Plugin not found: expo-build-properties(PLUGIN_NOT_FOUND)`
> 
> I've installed it with `npm i` and `expo`, neither helps. App builds fine in sim but crashes on device (the classic tale).

Did you resolve this?

**Comment by RemLawrence** [comment]
> In my `app.json`, `expo-build-properties` keeps giving me a warning in VSCode:
> 
> `Plugin not found: expo-build-properties(PLUGIN_NOT_FOUND)`
> 
> I've installed it with `npm i` and `expo`, neither helps. App builds fine in sim but crashes on device (the classic tale).

Hey, were you able to resolve this?

**Comment by alextbogdanov** [comment]
+1

**Comment by brentvatne** [comment]
install it in your app with `npx expo install expo-build-properties`

as an aside, this repository is a temporary home for config plugins until libraries create their own. the ffmpeg config plugin has been here too long and we are not the right people to be maintaining it, as we do not know anything about that react-native library. i'd suggest opening a pr to add it to the ffmpeg library of your choice and then opening a pr here to delete the config plugin from this repo.
