### ISSUE TITLE
React Native Branch incompatibility with Expo SDK 54: iOS Build fails with "cannot find type 'RCTBridge' in scope"

### ISSUE THREAD

**Issue by dcatindoy** [expo/config-plugins#294]
### Summary

When using Expo SDK 54 with `@config-plugins/react-native-branch` (`v10.0.0` or `v11.0.0`) and `react-native-branch`, the iOS EAS Build fails with the following error:

```
error: cannot find type 'RCTBridge' in scope
```

### Config Plugin

@config-plugins/react-native-branch

### What platform(s) does this occur on?

iOS

### SDK Version

54

### Steps to Reproduce

1. Create a new Expo project with SDK 54.
2. Install `react-native-branch` and `@config-plugins/react-native-branch` (latest versions).
3. Add the recommended configuration to `app.json`.
4. Run an EAS Build for iOS.

### Reproducible Example

* Repository: [[RCTBridge Issue (SDK 54)](https://github.com/dcatindoy/rctbridge-issue-sdk54)](https://github.com/dcatindoy/rctbridge-issue-sdk54)

**Comment by hassankhan** [comment]
Hi @dcatindoy, your repro is missing the config plugin from `app.json`. [See the example app for reference](https://github.com/expo/config-plugins/blob/bd1ffe70c596fbcd8a49e31dd37f1f36857a8109/apps/react-native-branch/app.json).

**Comment by MoritzCooks** [comment]
To clear up some confusion because at least I got a little stuck here due to this [README](https://github.com/expo/config-plugins/tree/main/packages/react-native-branch) which is mentioning matching versions for Branch.

I got it to compile and build on Xcode 26.4 with the following setup:

- "expo": "^53.0.0",
- "@config-plugins/react-native-branch": "^12.0.0",
-  "react-native-branch": "~6.6.0",
