### ISSUE TITLE
React Native Branch Config Plugin causing error with expo sdk 53

### ISSUE THREAD

**Issue by naviniitk** [expo/config-plugins#270]
### Summary

When I upgraded my expo sdk version to 53, suddenly ios build was not working and kept getting this error
```

❌  (ios/Leher/AppDelegate.swift:58:39)

  56 |   // Extension point for config-plugins
  57 | 
> 58 |   override func sourceURL(for bridge: RCTBridge) -> URL? {
     |                                       ^ cannot find type 'RCTBridge' in scope
  59 |     // needed to return the correct URL for expo-dev-client.
  60 |     bridge.bundleURL ?? bundleURL()
  61 |   }


❌  (ios/Leher/AppDelegate.swift:58:17)

  56 |   // Extension point for config-plugins
  57 | 
> 58 |   override func sourceURL(for bridge: RCTBridge) -> URL? {
     |                 ^ method does not override any method from its superclass
  59 |     // needed to return the correct URL for expo-dev-client.
  60 |     bridge.bundleURL ?? bundleURL()
  61 |   }
```
I had tried to create a new project and one by one adding the dependencies and found out that it is the issue with react native branch config plugin.

### Config Plugin

@config-plugins/react-native-branch

### What platform(s) does this occur on?

iOS

### SDK Version

53

### Reproducible demo

Create new repo
run `npx expo install react-native-branch @config-plugins/react-native-branch`
create prebuild with `npx expo prebuild --clean`
run command `yarn ios --no-build-cache`
This causes the above error

**Comment by radko93** [comment]
I can confirm this issue with 53.

**Comment by naviniitk** [comment]
Is there any workaround we can do for the time being?

**Comment by radko93** [comment]
I made a workaround for this, I patched RN branch

```
diff --git a/ios/RNBranch-Bridging-Header.h b/ios/RNBranch-Bridging-Header.h
new file mode 100644
index 0000000000000000000000000000000000000000..84805a30e1a7d7539ed5f133439c3e4e5c10dc51
--- /dev/null
+++ b/ios/RNBranch-Bridging-Header.h
@@ -0,0 +1,5 @@
+//
+//  Use this file to import your target's public headers that you would like to expose to Swift.
+//
+
+#import <React/RCTBridgeModule.h>
diff --git a/ios/RNBranch.xcodeproj/project.pbxproj b/ios/RNBranch.xcodeproj/project.pbxproj
index 71e079e01978f3374443c75e23f0879098570ea7..74d8179f1300bbed9f6ddfd811647e9e1c2c26ec 100644
--- a/ios/RNBranch.xcodeproj/project.pbxproj
+++ b/ios/RNBranch.xcodeproj/project.pbxproj
@@ -29,6 +29,8 @@
 		7B9654561E96E328009C3CEE /* RNBranchEventEmitter.m in Sources */ = {isa = PBXBuildFile; fileRef = 7B9654541E96E328009C3CEE /* RNBranchEventEmitter.m */; };
 		7BA40F94225589C900EC6B4D /* Branch.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = 7BA40F93225589C900EC6B4D /* Branch.framework */; settings = {ATTRIBUTES = (Weak, ); }; };
 		7BE575131E205B8600C936E2 /* RNBranch.m in Sources */ = {isa = PBXBuildFile; fileRef = 148030EE1CCDF9FA004ABEA4 /* RNBranch.m */; };
+		83981C292DCD397600E20BBE /* RNBranch-Bridging-Header.h in Headers */ = {isa = PBXBuildFile; fileRef = 83981C282DCD397600E20BBE /* RNBranch-Bridging-Header.h */; };
+		83981C312DCD39B800E20BBE /* Dummy.swift in Sources */ = {isa = PBXBuildFile; fileRef = 83981C302DCD39B800E20BBE /* Dummy.swift */; };
 /* End PBXBuildFile section */
 
 /* Begin PBXCopyFilesBuildPhase section */
@@ -67,6 +69,9 @@
 		7B9654531E96E328009C3CEE /* RNBranchEventEmitter.h */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.c.h; path = RNBranchEventEmitter.h; sourceTree = "<group>"; };
 		7B9654541E96E328009C3CEE /* RNBranchEventEmitter.m */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.c.objc; path = RNBranchEventEmitter.m; sourceTree = "<group>"; };
 		7BA40F93225589C900EC6B4D /* Branch.framework */ = {isa = PBXFileReference; explicitFileType = wrapper.framework; path = Branch.framework; sourceTree = BUILT_PRODUCTS_DIR; };
+		83981C282DCD397600E20BBE /* RNBranch-Bridging-Header.h */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.c.h; path = "RNBranch-Bridging-Header.h"; sourceTree = "<group>"; };
+		83981C2F2DCD39B700E20BBE /* RNBranch-Bridging-Header.h */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.c.h; path = "RNBranch-Bridging-Header.h"; sourceTree = "<group>"; };
+		83981C302DCD39B800E20BBE /* Dummy.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = Dummy.swift; sourceTree = "<group>"; };
 		B3A3CC361C5B0A070016AC52 /* libRNBranch.a */ = {isa = PBXFileReference; explicitFileType = archive.ar; includeInIndex = 0; path = libRNBranch.a; sourceTree = BUILT_PRODUCTS_DIR; };
 /* End PBXFileReference section */
 
@@ -100,6 +105,8 @@
 		B3A3CC2D1C5B0A070016AC52 = {
 			isa = PBXGroup;
 			children = (
+				83981C302DCD39B800E20BBE /* Dummy.swift */,
+				83981C282DCD397600E20BBE /* RNBranch-Bridging-Header.h */,
 				7B0329691FD9A76F0010D948 /* BranchContentMetadata+RNBranch.h */,
 				7B0329681FD9A76E0010D948 /* BranchContentMetadata+RNBranch.m */,
 				7B7D273E1FCE3BD2008E3EDE /* BranchEvent+RNBranch.h */,
@@ -123,6 +130,7 @@
 				B3A3CC371C5B0A070016AC52 /* Products */,
 				7BFC39BB1FD60C4700F39C3A /* Recovered References */,
 				7BA40F92225589C900EC6B4D /* Frameworks */,
+				83981C2F2DCD39B700E20BBE /* RNBranch-Bridging-Header.h */,
 			);
 			sourceTree = "<group>";
 		};
@@ -143,6 +151,7 @@
 			files = (
 				7B3B27501E707CD7003ABDF4 /* RNBranchAgingItem.h in Headers */,
 				7B3FCB261E20626A008E38E2 /* RNBranch.h in Headers */,
+				83981C292DCD397600E20BBE /* RNBranch-Bridging-Header.h in Headers */,
 				7B1D33581E410DD200755B98 /* BranchUniversalObject+RNBranch.h in Headers */,
 				7B7D27401FCE3BD2008E3EDE /* BranchEvent+RNBranch.h in Headers */,
 				7B1D335C1E410DD200755B98 /* RNBranchProperty.h in Headers */,
@@ -186,6 +195,7 @@
 				TargetAttributes = {
 					B3A3CC351C5B0A070016AC52 = {
 						CreatedOnToolsVersion = 7.2;
+						LastSwiftMigration = 1630;
 					};
 				};
 			};
@@ -214,6 +224,7 @@
 			files = (
 				7B3B27551E707CF5003ABDF4 /* RNBranchAgingDictionary.m in Sources */,
 				7B1D33571E410DD200755B98 /* BranchLinkProperties+RNBranch.m in Sources */,
+				83981C312DCD39B800E20BBE /* Dummy.swift in Sources */,
 				7B1D335D1E410DD300755B98 /* RNBranchProperty.m in Sources */,
 				7B1D33591E410DD200755B98 /* BranchUniversalObject+RNBranch.m in Sources */,
 				7B7D27411FCE3BD2008E3EDE /* BranchEvent+RNBranch.m in Sources */,
@@ -337,6 +348,7 @@
 		B3A3CC401C5B0A070016AC52 /* Debug */ = {
 			isa = XCBuildConfiguration;
 			buildSettings = {
+				CLANG_ENABLE_MODULES = YES;
 				FRAMEWORK_SEARCH_PATHS = (
 					"$(BUILT_PRODUCTS_DIR)/Branch",
 					"$(SRCROOT)/../../../ios/Carthage/Build/iOS",
@@ -345,12 +357,16 @@
 				OTHER_LDFLAGS = "-ObjC";
 				PRODUCT_NAME = "$(TARGET_NAME)";
 				PUBLIC_HEADERS_FOLDER_PATH = "/usr/local/include/$(PRODUCT_NAME)";
+				SWIFT_OBJC_BRIDGING_HEADER = "RNBranch-Bridging-Header.h";
+				SWIFT_OPTIMIZATION_LEVEL = "-Onone";
+				SWIFT_VERSION = 6.0;
 			};
 			name = Debug;
 		};
 		B3A3CC411C5B0A070016AC52 /* Release */ = {
 			isa = XCBuildConfiguration;
 			buildSettings = {
+				CLANG_ENABLE_MODULES = YES;
 				FRAMEWORK_SEARCH_PATHS = (
 					"$(BUILT_PRODUCTS_DIR)/Branch",
 					"$(SRCROOT)/../../../ios/Carthage/Build/iOS",
@@ -359,6 +375,8 @@
 				OTHER_LDFLAGS = "-ObjC";
 				PRODUCT_NAME = "$(TARGET_NAME)";
 				PUBLIC_HEADERS_FOLDER_PATH = "/usr/local/include/$(PRODUCT_NAME)";
+				SWIFT_OBJC_BRIDGING_HEADER = "RNBranch-Bridging-Header.h";
+				SWIFT_VERSION = 6.0;
 			};
 			name = Release;
 		};
```

and the config plugin:
```
diff --git a/expo-module.config.json b/expo-module.config.json
index 7791660d3bd430d008dc60b100ec52e3f1cc07a1..e29a8408dbce354cd3bc996cf2c34ca6f25fb05c 100644
--- a/expo-module.config.json
+++ b/expo-module.config.json
@@ -1,9 +1,3 @@
 {
-  "platforms": [
-    "android",
-    "ios"
-  ],
-  "ios": {
-    "appDelegateSubscribers": ["BranchAppDelegate"]
-  }
+  "platforms": ["android", "ios"]
 }
```

Then I added a config plugin to manually edit AppDelegate:
```
const { withAppDelegate } = require("expo/config-plugins");

const withBranch = (config) => {
  return withAppDelegate(config, (appDelegateConfig) => {
    const { modResults } = appDelegateConfig;

    if (modResults.language === "swift") {
      // Add imports to Swift AppDelegate
      modResults.contents = addSwiftImports(modResults.contents);

      // Add Branch initialization in didFinishLaunchingWithOptions
      modResults.contents = addSwiftBranchInitialization(modResults.contents);

      // Add URL handling method
      modResults.contents = addSwiftURLMethod(modResults.contents);

      // Add continued user activity method
      modResults.contents = addSwiftContinueUserActivity(modResults.contents);
    }

    return appDelegateConfig;
  });
};

// Helper functions for Swift modifications
function addSwiftImports(contents) {
  // Only add if not already imported
  if (!contents.includes("import RNBranch")) {
    // Try to add after the last import statement
    if (contents.match(/import\s+[A-Za-z0-9_.]+\s*$/m)) {
      return contents.replace(
        /import\s+[A-Za-z0-9_.]+\s*$/m,
        (match) => `${match}\nimport RNBranch`,
      );
    }

    // If no import statements found at the end of lines, try to find any import
    if (contents.includes("import ")) {
      return contents.replace(
        /import\s+[A-Za-z0-9_.]+/,
        (match) => `${match}\nimport RNBranch`,
      );
    }

    // Last resort: add at the beginning of the file
    return `import RNBranch\n${contents}`;
  }
  return contents;
}

function addSwiftBranchInitialization(contents) {
  if (!contents.includes("RNBranch.initSession")) {
    return contents.replace(
      /func application.*?didFinishLaunchingWithOptions.*?\{/s,
      (match) =>
        `${match}\n    RNBranch.initSession(launchOptions: launchOptions, isReferrable: true)`,
    );
  }
  return contents;
}

function addSwiftURLMethod(contents) {
  const openURLMethod = `
  // Branch URL handling
  func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
    return RNBranch.application(app, open: url, options: options)
  }
`;

  if (!contents.includes("open url: URL, options:")) {
    return contents.replace(/}(\s*?)$/, `${openURLMethod}\n}$1`);
  }
  return contents;
}

function addSwiftContinueUserActivity(contents) {
  const continueUserActivityMethod = `
  // Branch deep link handling
  func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
    return RNBranch.continue(userActivity)
  }
`;

  if (!contents.includes("continue userActivity:")) {
    return contents.replace(/}(\s*?)$/, `${continueUserActivityMethod}\n}$1`);
  }
  return contents;
}

module.exports = withBranch;
```

**Comment by naviniitk** [comment]
I installed the version 6.6.0 and it does not have this file `ios/RNBranch-Bridging-Header.h`, also where are you adding this code? 
```
const { withAppDelegate } = require("expo/config-plugins");

const withBranch = (config) => {
  return withAppDelegate(config, (appDelegateConfig) => {
    const { modResults } = appDelegateConfig;
...
```

**Comment by joranb** [comment]
Seems like they are on it: https://github.com/expo/config-plugins/pull/272

**Comment by radko93** [comment]
@joranb this PR will probably not fix it because the issue is within react native branch.

**Comment by joranb** [comment]
@radko93 I see they target 6.6 for Expo SDK 53 in the PR. Sure it is not fixed there?

**Comment by OliverWeitman** [comment]
Any updates regarding this?

**Comment by brentvatne** [comment]
this is released now, but ideally this plugin should move into the branch package itself. at expo we're not the right people to be maintaining a branch library, since we do not use the service ourselves nor do we track the development of it

**Comment by joranb** [comment]
Unfortunately it doesn't seem to fix the bug: 

```
 56 |   // Extension point for config-plugins
  57 | 
> 58 |   override func sourceURL(for bridge: RCTBridge) -> URL? {
     |                                       ^ cannot find type 'RCTBridge' in scope
  59 |     // needed to return the correct URL for expo-dev-client.
  60 |     bridge.bundleURL ?? bundleURL()
  61 |   }

```
Still same issue with 10.0.0.

**Comment by OliverWeitman** [comment]
> +1 on the above error - I am using
> 
> ```
>     "@config-plugins/react-native-branch": "10.0.0",
>     "react-native-branch": "6.7.1",
> ```

Same here

**Comment by joranb** [comment]
Since the problem is within Branch, it can't be solved here. https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution
There is no issue reporting in their repo, so you have to send them an email.

https://help.branch.io/v1/docs/submit-a-ticket

I already did, but will probably not be prioritized before more people do the same. 

Suggest you two for instance to do the same @kev0960 @OliverWeitman 

I also suggested they include the config plugin in their lib so there is no longer a need for this dependency, but we will see how it goes. Expo support has not been a priority for them previously.

**Comment by hesscbjr** [comment]
same here - i am using
```
"@config-plugins/react-native-branch": "10.0.0",
"react-native-branch": "6.7.1",
```

**Comment by hesscbjr** [comment]
I managed to patch for
```
"@config-plugins/react-native-branch": "10.0.0",
"react-native-branch": "6.7.1",
```

In `patches/react-native-branch+6.7.1.patch`
```
diff --git a/node_modules/react-native-branch/ios/Dummy.swift b/node_modules/react-native-branch/ios/Dummy.swift
new file mode 100644
index 0000000..8b13789
--- /dev/null
+++ b/node_modules/react-native-branch/ios/Dummy.swift
@@ -0,0 +1 @@
+
diff --git a/node_modules/react-native-branch/ios/RNBranch-Bridging-Header.h b/node_modules/react-native-branch/ios/RNBranch-Bridging-Header.h
new file mode 100644
index 0000000..84805a3
--- /dev/null
+++ b/node_modules/react-native-branch/ios/RNBranch-Bridging-Header.h
@@ -0,0 +1,5 @@
+//
+//  Use this file to import your target's public headers that you would like to expose to Swift.
+//
+
+#import <React/RCTBridgeModule.h>
diff --git a/node_modules/react-native-branch/ios/RNBranch.xcodeproj/project.pbxproj b/node_modules/react-native-branch/ios/RNBranch.xcodeproj/project.pbxproj
index 71e079e..74d8179 100644
--- a/node_modules/react-native-branch/ios/RNBranch.xcodeproj/project.pbxproj
+++ b/node_modules/react-native-branch/ios/RNBranch.xcodeproj/project.pbxproj
@@ -29,6 +29,8 @@
 		7B9654561E96E328009C3CEE /* RNBranchEventEmitter.m in Sources */ = {isa = PBXBuildFile; fileRef = 7B9654541E96E328009C3CEE /* RNBranchEventEmitter.m */; };
 		7BA40F94225589C900EC6B4D /* Branch.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = 7BA40F93225589C900EC6B4D /* Branch.framework */; settings = {ATTRIBUTES = (Weak, ); }; };
 		7BE575131E205B8600C936E2 /* RNBranch.m in Sources */ = {isa = PBXBuildFile; fileRef = 148030EE1CCDF9FA004ABEA4 /* RNBranch.m */; };
+		83981C292DCD397600E20BBE /* RNBranch-Bridging-Header.h in Headers */ = {isa = PBXBuildFile; fileRef = 83981C282DCD397600E20BBE /* RNBranch-Bridging-Header.h */; };
+		83981C312DCD39B800E20BBE /* Dummy.swift in Sources */ = {isa = PBXBuildFile; fileRef = 83981C302DCD39B800E20BBE /* Dummy.swift */; };
 /* End PBXBuildFile section */
 
 /* Begin PBXCopyFilesBuildPhase section */
@@ -67,6 +69,9 @@
 		7B9654531E96E328009C3CEE /* RNBranchEventEmitter.h */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.c.h; path = RNBranchEventEmitter.h; sourceTree = "<group>"; };
 		7B9654541E96E328009C3CEE /* RNBranchEventEmitter.m */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.c.objc; path = RNBranchEventEmitter.m; sourceTree = "<group>"; };
 		7BA40F93225589C900EC6B4D /* Branch.framework */ = {isa = PBXFileReference; explicitFileType = wrapper.framework; path = Branch.framework; sourceTree = BUILT_PRODUCTS_DIR; };
+		83981C282DCD397600E20BBE /* RNBranch-Bridging-Header.h */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.c.h; path = "RNBranch-Bridging-Header.h"; sourceTree = "<group>"; };
+		83981C2F2DCD39B700E20BBE /* RNBranch-Bridging-Header.h */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.c.h; path = "RNBranch-Bridging-Header.h"; sourceTree = "<group>"; };
+		83981C302DCD39B800E20BBE /* Dummy.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = Dummy.swift; sourceTree = "<group>"; };
 		B3A3CC361C5B0A070016AC52 /* libRNBranch.a */ = {isa = PBXFileReference; explicitFileType = archive.ar; includeInIndex = 0; path = libRNBranch.a; sourceTree = BUILT_PRODUCTS_DIR; };
 /* End PBXFileReference section */
 
@@ -100,6 +105,8 @@
 		B3A3CC2D1C5B0A070016AC52 = {
 			isa = PBXGroup;
 			children = (
+				83981C302DCD39B800E20BBE /* Dummy.swift */,
+				83981C282DCD397600E20BBE /* RNBranch-Bridging-Header.h */,
 				7B0329691FD9A76F0010D948 /* BranchContentMetadata+RNBranch.h */,
 				7B0329681FD9A76E0010D948 /* BranchContentMetadata+RNBranch.m */,
 				7B7D273E1FCE3BD2008E3EDE /* BranchEvent+RNBranch.h */,
@@ -123,6 +130,7 @@
 				B3A3CC371C5B0A070016AC52 /* Products */,
 				7BFC39BB1FD60C4700F39C3A /* Recovered References */,
 				7BA40F92225589C900EC6B4D /* Frameworks */,
+				83981C2F2DCD39B700E20BBE /* RNBranch-Bridging-Header.h */,
 			);
 			sourceTree = "<group>";
 		};
@@ -143,6 +151,7 @@
 			files = (
 				7B3B27501E707CD7003ABDF4 /* RNBranchAgingItem.h in Headers */,
 				7B3FCB261E20626A008E38E2 /* RNBranch.h in Headers */,
+				83981C292DCD397600E20BBE /* RNBranch-Bridging-Header.h in Headers */,
 				7B1D33581E410DD200755B98 /* BranchUniversalObject+RNBranch.h in Headers */,
 				7B7D27401FCE3BD2008E3EDE /* BranchEvent+RNBranch.h in Headers */,
 				7B1D335C1E410DD200755B98 /* RNBranchProperty.h in Headers */,
@@ -186,6 +195,7 @@
 				TargetAttributes = {
 					B3A3CC351C5B0A070016AC52 = {
 						CreatedOnToolsVersion = 7.2;
+						LastSwiftMigration = 1630;
 					};
 				};
 			};
@@ -214,6 +224,7 @@
 			files = (
 				7B3B27551E707CF5003ABDF4 /* RNBranchAgingDictionary.m in Sources */,
 				7B1D33571E410DD200755B98 /* BranchLinkProperties+RNBranch.m in Sources */,
+				83981C312DCD39B800E20BBE /* Dummy.swift in Sources */,
 				7B1D335D1E410DD300755B98 /* RNBranchProperty.m in Sources */,
 				7B1D33591E410DD200755B98 /* BranchUniversalObject+RNBranch.m in Sources */,
 				7B7D27411FCE3BD2008E3EDE /* BranchEvent+RNBranch.m in Sources */,
@@ -337,6 +348,7 @@
 		B3A3CC401C5B0A070016AC52 /* Debug */ = {
 			isa = XCBuildConfiguration;
 			buildSettings = {
+				CLANG_ENABLE_MODULES = YES;
 				FRAMEWORK_SEARCH_PATHS = (
 					"$(BUILT_PRODUCTS_DIR)/Branch",
 					"$(SRCROOT)/../../../ios/Carthage/Build/iOS",
@@ -345,12 +357,16 @@
 				OTHER_LDFLAGS = "-ObjC";
 				PRODUCT_NAME = "$(TARGET_NAME)";
 				PUBLIC_HEADERS_FOLDER_PATH = "/usr/local/include/$(PRODUCT_NAME)";
+				SWIFT_OBJC_BRIDGING_HEADER = "RNBranch-Bridging-Header.h";
+				SWIFT_OPTIMIZATION_LEVEL = "-Onone";
+				SWIFT_VERSION = 6.0;
 			};
 			name = Debug;
 		};
 		B3A3CC411C5B0A070016AC52 /* Release */ = {
 			isa = XCBuildConfiguration;
 			buildSettings = {
+				CLANG_ENABLE_MODULES = YES;
 				FRAMEWORK_SEARCH_PATHS = (
 					"$(BUILT_PRODUCTS_DIR)/Branch",
 					"$(SRCROOT)/../../../ios/Carthage/Build/iOS",
@@ -359,6 +375,8 @@
 				OTHER_LDFLAGS = "-ObjC";
 				PRODUCT_NAME = "$(TARGET_NAME)";
 				PUBLIC_HEADERS_FOLDER_PATH = "/usr/local/include/$(PRODUCT_NAME)";
+				SWIFT_OBJC_BRIDGING_HEADER = "RNBranch-Bridging-Header.h";
+				SWIFT_VERSION = 6.0;
 			};
 			name = Release;
 		}; 
```

Then, in `patches/@config-plugins+react-native-branch+10.0.0.patch`

```
diff --git a/node_modules/@config-plugins/react-native-branch/expo-module.config.json b/node_modules/@config-plugins/react-native-branch/expo-module.config.json
index 7791660..e29a840 100644
--- a/node_modules/@config-plugins/react-native-branch/expo-module.config.json
+++ b/node_modules/@config-plugins/react-native-branch/expo-module.config.json
@@ -1,9 +1,3 @@
 {
-  "platforms": [
-    "android",
-    "ios"
-  ],
-  "ios": {
-    "appDelegateSubscribers": ["BranchAppDelegate"]
-  }
+  "platforms": ["android", "ios"]
 }
```

Then I created a custom `plugins/withBranch.js`

```
const { withAppDelegate } = require("expo/config-plugins");

const withBranch = (config) => {
  return withAppDelegate(config, (appDelegateConfig) => {
    const { modResults } = appDelegateConfig;

    if (modResults.language === "swift") {
      // Add imports to Swift AppDelegate
      modResults.contents = addSwiftImports(modResults.contents);

      // Add Branch initialization in didFinishLaunchingWithOptions
      modResults.contents = addSwiftBranchInitialization(modResults.contents);

      // Modify existing URL handling method to include Branch
      modResults.contents = modifySwiftURLMethod(modResults.contents);

      // Modify existing continued user activity method to include Branch
      modResults.contents = modifySwiftContinueUserActivity(modResults.contents);
    }

    return appDelegateConfig;
  });
};

// Helper functions for Swift modifications
function addSwiftImports(contents) {
  // Only add if not already imported
  if (!contents.includes("import RNBranch")) {
    // Try to add after the last import statement
    if (contents.match(/import\s+[A-Za-z0-9_.]+\s*$/m)) {
      return contents.replace(
        /import\s+[A-Za-z0-9_.]+\s*$/m,
        (match) => `${match}\nimport RNBranch`,
      );
    }

    // If no import statements found at the end of lines, try to find any import
    if (contents.includes("import ")) {
      return contents.replace(
        /import\s+[A-Za-z0-9_.]+/,
        (match) => `${match}\nimport RNBranch`,
      );
    }

    // Last resort: add at the beginning of the file
    return `import RNBranch\n${contents}`;
  }
  return contents;
}

function addSwiftBranchInitialization(contents) {
  if (!contents.includes("RNBranch.initSession")) {
    return contents.replace(
      /func application.*?didFinishLaunchingWithOptions.*?\{/s,
      (match) =>
        `${match}\n    RNBranch.initSession(launchOptions: launchOptions, isReferrable: true)`,
    );
  }
  return contents;
}

function modifySwiftURLMethod(contents) {
  // Find and modify the existing open URL method to include Branch
  if (!contents.includes("RNBranch.application(app, open: url")) {
    // Look for the existing URL method and modify it
    return contents.replace(
      /return super\.application\(app, open: url, options: options\) \|\| RCTLinkingManager\.application\(app, open: url, options: options\)/,
      `return super.application(app, open: url, options: options) || RCTLinkingManager.application(app, open: url, options: options) || RNBranch.application(app, open: url, options: options)`
    );
  }
  return contents;
}

function modifySwiftContinueUserActivity(contents) {
  // Find and modify the existing continue userActivity method to include Branch
  if (!contents.includes("RNBranch.continue(userActivity)")) {
    // Look for the existing continue userActivity method and modify it
    return contents.replace(
      /let result = RCTLinkingManager\.application\(application, continue: userActivity, restorationHandler: restorationHandler\)\s*return super\.application\(application, continue: userActivity, restorationHandler: restorationHandler\) \|\| result/,
      `let result = RCTLinkingManager.application(application, continue: userActivity, restorationHandler: restorationHandler)
    let branchResult = RNBranch.continue(userActivity)
    return super.application(application, continue: userActivity, restorationHandler: restorationHandler) || result || branchResult`
    );
  }
  return contents;
}

module.exports = withBranch; 
```

**Comment by naviniitk** [comment]
> I managed to patch for
> 
> ```
> "@config-plugins/react-native-branch": "10.0.0",
> ...
> ```

Hey, this compiles the app properly but then I get the error: `[runtime not ready]: TypeError: Cannot read property 'STANDARD_EVENT_ADD_TO_CART' of null, js engine: hermes`
Have you faced this? @hesscbjr 
@
